---
- name: Configure | ensure enough vm huge pages
  ansible.posix.sysctl:
    name: vm.nr_hugepages
    value: "{{ postgresql_num_huge_pages }}"
    state: present
    sysctl_set: true
  notify:
    - Reboot
  tags:
    - no_testing

- name: Configure | ensure vm.swappiness is 5
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '5'
    state: present
    sysctl_set: true
  tags:
    - no_testing

- name: Configure | ensure postgres user owns home dir
  ansible.builtin.file:
    path: /var/lib/postgresql
    state: directory
    owner: postgres
    group: postgres
    recurse: true

- name: Configure | ensure archive dir exists
  ansible.builtin.file:
    state: directory
    path: "{{ postgresql_db_path }}/archive"
    owner: postgres
    group: postgres
    mode: "0770"

- name: Configure | ensure config dir exists
  ansible.builtin.file:
    state: directory
    path: "{{ postgresql_conf_path }}/conf.d"
    owner: postgres
    group: postgres
    mode: u+rx

- name: Configure | template configs
  ansible.builtin.template:
    src: cyverse.conf.j2
    dest: "{{ postgresql_conf_path }}/conf.d/cyverse.conf"
    owner: postgres
    group: postgres
    mode: "0640"
  notify:
    - Restart postgres

- name: Configure | ensure block in pg_hba.conf exists
  ansible.builtin.blockinfile:
    path: "{{ postgresql_conf_path }}/pg_hba.conf"
    create: true
    mode: u+r
    insertafter: "{{ postgresql_hba_insertafter }}"
    marker: "# {mark} postgresql MANAGED BLOCK2"
    block: |
      {% for entry in postgresql_hba_users %}
      {{ entry }}
      {% endfor %}
      {% if postgresql_upstream_node %}
      {%   set ip =
             postgresql_upstream_node if postgresql_upstream_node | ansible.utils.ipaddr else
             lookup('dig', postgresql_upstream_node) %}
      {{ '%-7s %-15s %-15s %-23s %s'
        | format('host', 'replication', postgresql_replication_username, ip ~ '/32', 'trust') }}
      {% endif %}
      {% for replica in postgresql_downstream_nodes %}
      {%   set ip = replica if replica | ansible.utils.ipaddr else lookup('dig', replica) %}
      {{ '%-7s %-15s %-15s %-23s %s'
        | format('host', 'replication', postgresql_replication_username, ip ~ '/32', 'trust') }}
      {% endfor %}
  notify:
    - Reload postgres

- name: Configure | template pgpass file
  ansible.builtin.template:
    src: pgpass.j2
    dest: /var/lib/postgresql/.pgpass
    owner: postgres
    group: postgres
    mode: "0600"
  when: postgresql_upstream_node or postgresql_downstream_nodes|length > 0
