---

- name: Variables | verify required vars exist
  ansible.builtin.assert:
    that:
      - postgresql_replication_username is defined
      - postgresql_replication_password is defined
  when: postgresql_upstream_node or postgresql_downstream_nodes|length > 0
