---
- name: Converge | client deposition
  hosts: all
  gather_facts: false
  tasks:
    - name: Place default client env file
      ansible.builtin.include_role:
        name: cyverse.ds.irods_cfg
        tasks_from: client.yml

    - name: Place custom client env file
      ansible.builtin.include_role:
        name: cyverse.ds.irods_cfg
        tasks_from: client.yml
      vars:
        irods_cfg_chown: false
        irods_cfg_environment_file: tmp/ie.json
