---
- name: Base | prepare
  ansible.builtin.import_playbook: ../_irods_cfg_shared/prepare.yml


- name: Prepare
  hosts: all
  tasks:
    - name: Create irods user
      ansible.builtin.user:
        name: irods

    - name: Download client env schema
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/irods/irods/refs/tags/4.3.1/schemas/configuration/v4/client_environment.json.in
        dest: /
        mode: u+r
        timeout: 120
      register: download
      until: download is not failed
      retries: 1
