---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: rabbitmq_vhost
    pre_build_image: false
    dockerfile: Dockerfile
    override_command: false
provisioner:
  name: ansible
verifier:
  name: ansible
