---
driver:
  name: docker
platforms:
  - name: alma9.localdomain
    image: alma9-irods
    pre_build_image: false
    dockerfile: ../_irods_cfg_shared/alma9.dockerfile
    hostname: alma9.localdomain
    shm_size: 256m
provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        vars:
          ansible_python_interpreter: /usr/bin/python3
          irods_cfg_validate: true
      irods_catalog:
        hosts:
          alma9.localdomain:
            irods_cfg_database:
              db_host: 127.0.0.1
              db_odbc_driver: PostgreSQL
              db_password: testpassword
              db_username: irods
            pg_hba_path: /var/lib/pgsql/data/pg_hba.conf
