---
_dbms_restart_allowed: "{{ dbms_restart_allowed | d(false) }}"
_dbms_reboot_allowed: "{{ dbms_reboot_allowed | d(false) }}"

_dbms_checkpoint_completion_target: "{{ dbms_checkpoint_completion_target | d(0.9) }}"
_dbms_checkpoint_timeout: "{{ dbms_checkpoint_timeout | d(15) }}"

_dbms_effective_io_concurrency: "{{ dbms_effective_io_concurrency | d(200) }}"

_dbms_log_line_prefix: "{{ dbms_log_line_prefix | d('< %m %r >') }}"
_dbms_log_min_duration: "{{ dbms_log_min_duration | d(1000) }}"

_dbms_maintenance_work_mem: "{{ dbms_maintenance_work_mem | d(2) }}"

_dbms_max_connections: "{{ dbms_max_connections | d(500) }}"

_dbms_pg_hba: "{{ dbms_pg_hba | d('/etc/postgresql/12/main/pg_hba.conf') }}"

_dbms_port: "{{ dbms_port | d(5432) }}"

_dbms_effective_cache_size: "{{ dbms_effective_cache_size | d(None) }}"
_dbms_random_page_cost: "{{ dbms_random_page_cost | d(1.1) }}"

_dbms_replication_password: "{{ dbms_replication_password | d(None) }}"
_dbms_replication_start: "{{ dbms_replication_start | d(false) }}"
_dbms_replication_username: "{{ dbms_replication_username | d('postgres') }}"

_dbms_wal_keep_segments: "{{ dbms_wal_keep_segments | d(4000) }}"
_dbms_max_wal_senders: "{{ dbms_max_wal_senders | d(120) }}"
_dbms_max_wal_size: "{{ dbms_max_wal_size | d(8) }}"
_dbms_min_wal_size: "{{ dbms_min_wal_size | d(2) }}"

_dbms_work_mem: "{{ dbms_work_mem | d(32) }}"

_dbms_mem_num_huge_pages: "{{ dbms_mem_num_huge_pages | d(60000) }}"

_dbms_max_worker_processes: "{{ dbms_max_worker_processes | d(None) }}"
_dbms_max_parallel_maintenance_workers: "{{ dbms_max_parallel_maintenance_workers | d(2) }}"
_dbms_max_parallel_workers_per_gather: "{{ dbms_max_parallel_workers_per_gather | d(2) }}"

_dbms_irods_username: "{{ dbms_irods_username | d('irods') }}"
_dbms_irods_password: "{{ dbms_irods_password | mandatory }}"