---
_irods_admin_password: "{{ irods_admin_password | d(_irods_clerver_password) }}"
_irods_admin_username: "{{ irods_admin_username | d(_irods_clerver_user) }}"
_irods_allowed_clients: "{{ irods_allowed_src | d('0.0.0.0/0') }}"
_irods_amqp_exchange: "{{ irods_amqp_exchange | d('irods') }}"
_irods_amqp_host: "{{ irods_amqp_host | d('localhost') }}"
_irods_amqp_port: "{{ irods_amqp_port | d(5672) }}"
_irods_amqp_username: "{{ irods_amqp_username | d('guest') }}"
_irods_amqp_password: "{{ irods_amqp_password | d('guest') }}"
_irods_amqp_vhost: "{{ irods_amqp_vhost | d('/') }}"
_irods_become_svc_acnt: "{{ irods_become_svc_acnt | d(true) }}"
_irods_build_dir: "{{ irods_build_dir | d('/tmp') }}"
_irods_canonical_hostname: "{{ irods_canonical_hostname | d(groups['irods_catalog'][0]) }}"
_irods_canonical_zone_port: "{{ irods_canonical_zone_port | d(_irods_zone_port) }}"
_irods_check_routes_timeout: "{{ irods_check_routes_timeout | d(3) }}"
_irods_clerver_password: "{{ irods_clerver_password | d('rods') }}"
_irods_clerver_user: "{{ irods_clerver_user | d('rods') }}"
_irods_db_password: "{{ irods_db_password | d('testpassword') }}"
_irods_db_user: "{{ irods_db_user | d('irods') }}"
_irods_dbms_host: "{{ irods_dbms_host | d(groups['irods_catalog'][0]) }}"
_irods_dbms_pg_hba: "{{ irods_dbms_pg_hba | d('/etc/postgresql/12/main/pg_hba.conf') }}"
_irods_dbms_port: "{{ irods_dbms_port | d(5432) }}"
_irods_default_dir_mode: "{{ irods_default_dir_mode | d('0750') }}"
_irods_default_file_mode: "{{ irods_default_file_mode | d('0600') }}"
_irods_default_number_of_transfer_threads: "{{ irods_default_number_of_transfer_threads | d(3) }}"
_irods_default_repl_resource: "{{ irods_default_repl_resource | d(_irods_default_resource) }}"
_irods_default_resource: "{{ irods_default_resource | d(_irods_resource_hierarchies[0].name) }}"
_irods_default_vault: "{{ irods_default_vault | d(None) }}"
_irods_federation: "{{ irods_federation | d([]) }}"
_irods_host_aliases: "{{ irods_host_aliases | d([]) }}"
_irods_init_repl_delay: "{{ irods_init_repl_delay | d(0) }}"
_irods_max_num_re_procs: "{{ irods_max_num_re_procs | d(4) }}"
_irods_negotiation_key: "{{ irods_negotiation_key | d(None) }}"
_irods_odbc_driver: "{{ irods_odbc_driver| d('PostgreSQL') }}"
_irods_other_host_entries: "{{ irods_other_host_entries | d([]) }}"
_irods_parallel_transfer_buffer_size: "{{ irods_parallel_transfer_buffer_size | d(100) }}"
_irods_publish_rs_image: "{{ irods_publish_rs_image | d(false) }}"
_irods_re_host: "{{ irods_re_host | d(groups['irods_catalog'][0]) }}"
_irods_report_email_addr: "{{ irods_report_email_addr | d('root@localhost') }}"
_irods_resource_hierarchies: >-
  {{
    irods_resource_hierarchies
      if irods_resource_hierarchies is defined and irods_resource_hierarchies|length > 0 else
    [ { "name": "demoResc" } ] }}
_irods_restart_allowed: "{{ irods_restart_allowed | d(false) }}"
_irods_rs_image: "{{ irods_rs_image | d('ds-irods-rs-onbuild') }}"
_irods_s3_cred: "{{ irods_s3_cred | d([]) }}"
_irods_server_control_plane_key: "{{ irods_server_control_plane_key | d(None) }}"
_irods_server_port_range_end: "{{ irods_server_port_range_end | d(20199) }}"
_irods_server_port_range_start: "{{ irods_server_port_range_start | d(20000) }}"
_irods_service_account_name: "{{ irods_service_account_name | d('irods') }}"
_irods_service_group_name: "{{ irods_service_group_name | d(_irods_service_account_name) }}"
_irods_storage_resources: "{{ irods_storage_resources | d([]) }}"
_irods_sysctl_kernel: "{{ irods_sysctl_kernel | d([]) }}"
_irods_user_password_salt: "{{ irods_user_password_salt | d(None) }}"
_irods_version: "{{ irods_version | d('4.3.1') }}"
_irods_zone_key: "{{ irods_zone_key | d(None) }}"
_irods_zone_name: "{{ irods_zone_name | d('tempZone') }}"


# The following are internal constants

_irods_client_server_policy: CS_NEG_REFUSE
_irods_default_hash_scheme: MD5
_irods_server_control_plane_port: 1248
_irods_zone_port: 1247
