#!/usr/bin/env bash
#
# This script builds the Docker images that compose the testing environment and
# the ansible-tester image.
#
# © 2025 The Arizona Board of Regents on behalf of The University of Arizona.
# For license information, see https://cyverse.org/license.

set -o errexit -o nounset -o pipefail

BASE_DIR="$(dirname "$(realpath --canonicalize-existing "$0")")"
readonly BASE_DIR

main() {
	"$BASE_DIR"/env/build "$BASE_DIR"/config.inc
	"$BASE_DIR"/ansible-tester/build "$BASE_DIR"/config.inc
}

main "$@"
