#!/usr/bin/env bash
#
# This script removes the images built by the build script. Specifically, it
# deletes ansible-tester, all of the images composing env, and the base image
# ansible-support.

#shellcheck source=testing/portability.inc
. "$(cd -- "$(dirname -- "$0")" && pwd -P)"/portability.inc

ExecName=$(ds_canonicalize "$0")
readonly ExecName


main()
{
  local baseDir
  baseDir=$(dirname "$ExecName")

  "$baseDir"/ansible-tester/clean
  "$baseDir"/env/clean "$baseDir"/config.inc
}


main "$@"
