#!/usr/bin/env bash
#
# © 2025 The Arizona Board of Regents on behalf of The University of Arizona.
# For license information, see https://cyverse.org/license.

show_help() {
	cat <<EOF

$ExecName

Usage:
$ExecName [options]

test Data Store playbooks

Options:
 -I, --inventory <inventory>  the name of the inventory hosts file to use
 -P, --playbook <playbook>    the name of the playbook to test
 -S, --setup <playbooks>      a comma-separated list of playbook to be run, in
                              order, prior to the playbook under test
 -h, --help                   show help and exit
 -i, --inspect                after running the playbook, open a shell that
                              allows manual inspection of the configuration
                              files, vaults, and logs
 -p, --pretty                 more information will be output and newlines will
                              be expanded in that output.

Summary:
This script runs a playbook with in the testing environment. If no inventory
hosts file is provided, it will use 'hosts-all'. If no playbook is provided, no
playbook will be run. When combined with -i, this allows the environment to be
started in interactive mode.
EOF
}


set -o errexit -o nounset -o pipefail

ExecName=$(readlink -f "$0")
TestingDir=$(dirname "$ExecName")
CollectionDir="$(dirname "$TestingDir")"
readonly ExecName TestingDir CollectionDir

#shellcheck source=testing/portability.sh
source "$TestingDir"/portability.sh

portability::require_bash 4

readonly Cfg="$TestingDir"/config.inc
readonly PlaybooksDir="$CollectionDir"/playbooks
readonly DefaultHosts=hosts-all

# Printed by both the irods_ctl module and setup_irods.py when the server can't start
readonly IrodsStartFailure='iRODS server failed to \(re\)\?start'


# shellcheck disable=SC1090
source "$Cfg"


main() {
	declare -A opts=(
		[help]=''
		[inspect]=''
		[inventory]="$DefaultHosts"
		[playbook]=''
		[pretty]=''
		[setup]='' )

	if ! resolve_opts opts "$@"
	then
		exit_with_help
	fi

	if [[ -n "${opts[help]}" ]]
	then
		show_help
		return
	fi

	local playbook
	if [[ -n "${opts[playbook]}" ]]
	then
		playbook="$(resolve_playbook "${opts[playbook]}")"
	fi

	local setup
	if [[ -n "${opts[setup]}" ]]
	then
		local books
		IFS=, read -r -a books <<< "${opts[setup]}"

		local book
		for book in "${books[@]}"
		do
			book="$(resolve_playbook "$book")"

			if [[ -n "${setup-}" ]]
			then
				setup="$setup","$book"
			else
				setup="$book"
			fi
		done
	fi

	do_run \
		"${opts[inspect]}" \
		"${opts[pretty]}" \
		"${opts[inventory]}" \
		"${setup-}" \
		"${playbook-}"
}


resolve_opts() {
	local optsVar="$1"
	shift

	local args
	args="$(parse_cmd_line "$@")"
	eval set -- "$args"

	while true
	do
		case "$1" in
			-h|--help)
				eval "$optsVar"[help]=help
				shift 1
				;;
			-I|--inventory-hosts)
				eval "$optsVar""[inventory]='$2'"
				shift 2
				;;
			-i|--inspect)
				eval "$optsVar"[inspect]=inspect
				shift 1
				;;
			-P|--playbook)
				eval "$optsVar""[playbook]='$2'"
				shift 2
				;;
			-p|--pretty)
				eval "$optsVar"'[pretty]=pretty'
				shift 1
				;;
			-S|--setup)
				eval "$optsVar""[setup]='$2'"
				shift 2
				;;
			--)
				shift 1
				break
				;;
		esac
	done
}


# iRODS 4.3.1 sometimes segfaults while starting (irods/irods#7747, fixed in
# 4.3.3), so a run that fails this way is retried once in a fresh environment.
do_run() {
	local doInspect="$1"

	local output
	output="$(mktemp)"
	# shellcheck disable=SC2064
	trap "rm --force '$output'" EXIT

	if run_in_env "$output" "$@"
	then
		return 0
	fi

	if [[ -n "$doInspect" ]] || ! grep --quiet --regexp "$IrodsStartFailure" "$output"
	then
		return 1
	fi

	cat <<'EOF' >&2
An iRODS server failed to start. This is usually the iRODS 4.3.1 startup
segfault (irods/irods#7747), which "journalctl -k | grep irodsServer" on the
host confirms. Retrying once in a fresh environment.
EOF
	run_in_env "$output" "$@"
}


run_in_env() {
	local output="$1"
	local doInspect="$2"
	local pretty="$3"
	local hosts="$4"
	local setup="$5"
	local playbook="$6"

	"$TestingDir"/env/controller "$Cfg" start

	local tester=(
		"$TestingDir"/ansible-tester/run
		"$doInspect" "$pretty" '' "$hosts" "$CollectionDir" "$setup" "$playbook" )

	local rc
	if [[ -n "$doInspect" ]]
	then
		# The inspection shell needs the terminal, so its output isn't captured.
		"${tester[@]}" || rc=1
	else
		"${tester[@]}" | tee "$output" || rc=1
	fi

	"$TestingDir"/env/controller "$Cfg" stop
	return ${rc-0}
}


exit_with_help() {
	show_help >&2
	exit 1
}


parse_cmd_line() {
	local opts
	opts="$(\
		portability::getopt \
			hiI:P:pS: \
			help,inspect,inventory:,playbook:,pretty,setup: \
			"$ExecName" \
			"$@" )"

	local ret="$?"

	if [ "$ret" -ne 0 ]
	then
		exit_with_help
	fi

	printf '%s' "$opts"
}


resolve_playbook() {
	local playbook="$1"

	if [[ "$playbook" != *.* ]]
	then
		playbook="$playbook".yml
	fi

	if ! [ -f "$PlaybooksDir"/"$playbook" ]
	then
		printf 'The playbook %s does not exist\n' "$playbook" >&2
		exit 1
	fi

	printf '%s' "$playbook"
}


main "$@"
