FROM test-env-base:alma9

ADD https://packages.irods.org/renci-irods.yum.repo /etc/yum.repos.d/renci-irods.yum.repo

# An older davrods with its irods-runtime locked, so webdav.yml's upgrade path gets tested
RUN <<'EOF'
	set -o errexit
	rpm --import https://packages.irods.org/irods-signing-key.asc
	yum --assumeyes updateinfo
	dnf --assumeyes install \
		https://github.com/UtrechtUniversity/davrods/releases/download/4.3.3_1.5.1/davrods-4.3.3_1.5.1-1.rpm
	yum versionlock add irods-runtime-4.3.3
	dnf clean all
	rm --force --recursive /var/cache/dnf
EOF
