FROM test-env-base:alma9

ARG IRODS_CATALOG_PROVIDER=csp
ARG IRODS_CONTROL_PLANE_KEY=TEMPORARY__32byte_ctrl_plane_key
ARG IRODS_CONTROL_PLANE_PORT=1248
ARG IRODS_DEFAULT_RESOURCE=demoResc
ARG IRODS_DEFAULT_VAULT=/var/lib/irods/Vault
ARG IRODS_FIRST_EPHEMERAL_PORT=20000
ARG IRODS_HOST=rs
ARG IRODS_LAST_EPHEMERAL_PORT=20199
ARG IRODS_NEGOTIATION_KEY=TEMPORARY_32byte_negotiation_key
ARG IRODS_SCHEMA_VALIDATION=https://schemas.irods.org/configuration
ARG IRODS_SYSTEM_GROUP=irods
ARG IRODS_SYSTEM_USER=irods
ARG IRODS_VERSION=4.3.1
ARG IRODS_ZONE_KEY=TEMPORARY_zone_key
ARG IRODS_ZONE_NAME=tempZone
ARG IRODS_ZONE_PASSWORD=rods
ARG IRODS_ZONE_PORT=1247
ARG IRODS_ZONE_USER=rods

ADD https://packages.irods.org/renci-irods.yum.repo /etc/yum.repos.d/renci-irods.yum.repo

RUN \
	--mount=target=/tmp/config-irods,source=irods-consumer/scripts/config-irods.sh \
	--mount=target=/tmp/service.sh.template,source=irods-consumer/scripts/service.sh.template \
	--mount=target=/tmp/prep-svc-script,source=irods-consumer/scripts/prep-svc-script.sh \
<<EOF
	set -o errexit

### Install iRODS
	rpm --import https://packages.irods.org/irods-signing-key.asc
# XXX - irods-server needs irods-icommands but doesn't declare it as a dependency
	dnf --assumeyes install \
		irods-icommands-"$IRODS_VERSION" \
		irods-runtime-"$IRODS_VERSION" \
		irods-server-"$IRODS_VERSION" \
		rsyslog
# XXX - ^^^
	yum versionlock add \
		irods-icommands-"$IRODS_VERSION" \
		irods-runtime-"$IRODS_VERSION" \
		irods-server-"$IRODS_VERSION"

# The EL9 repository has NetCDF modules for iRODS 4.3.1 only.
	if dnf --assumeyes --quiet list --available irods-netcdf-server_modules-"$IRODS_VERSION".0 \
		> /dev/null 2>&1
	then
		dnf --assumeyes install \
			irods-netcdf-client_modules-"$IRODS_VERSION".0 \
			irods-netcdf-icommands-"$IRODS_VERSION".0 \
			irods-netcdf-server_modules-"$IRODS_VERSION".0
		yum versionlock add \
			irods-netcdf-client_modules-"$IRODS_VERSION".0 \
			irods-netcdf-icommands-"$IRODS_VERSION".0 \
			irods-netcdf-server_modules-"$IRODS_VERSION".0
	fi

	python3 -m pip install 'python-irodsclient<3.2'

### Configure iRODS
	/tmp/config-irods

### Create service script
	/tmp/prep-svc-script

### Populate .ssh/authorized_keys
	printf '%s %s %s\n' \
			ssh-ed25519 \
			AAAAC3NzaC1lZDI1NTE5AAAAIMNAkCWfBgthPFt3580sM8H0BXpCQVrEI8Y2Kpq9bO+3 \
			disallowed \
		> /root/.ssh/authorized_keys

### Clean dnf cache
	dnf clean all
	rm --force --recursive /var/cache/dnf
EOF

COPY irods-consumer/config/profile-irods.sh /etc/profile.d/irods.sh
COPY irods-consumer/config/rsyslog-irods.conf /etc/rsyslog.conf
COPY irods-consumer/config/logrotate-irods /etc/logrotate.d/irods

CMD [ "/service.sh" ]
