---
- name: Determine if already initialized
  ansible.builtin.stat:
    path: "{{ _root_dir }}/var/lib/irods/version.json"
  register: version

- name: Setup iRODS | Initialize ICAT schema if needed
  when: not version.stat.exists
  block:
    - name: Load variable values
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - server_config.yml
        - irods_environment_server.yml

    - name: Create setup configuration file
      ansible.builtin.template:
        src: setup_configuration.json.j2
        dest: /tmp/setup_configuration.json
        mode: u+rw
# XXX - Workaround for https://github.com/irods/irods/issues/8297
      vars:
        irods_cfg_default_resource_name: tmp-{{ inventory_hostname_short }}
# XXX - ^^^

    - name: Setup iRODS
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |
          set -o errexit
          python3 /var/lib/irods/scripts/setup_irods.py --stdout --verbose \
            --json_configuration_file=/tmp/setup_configuration.json
          printf '\n' >> /var/lib/irods/.irods/irods_environment.json
          rm --force /var/lib/irods/log/test_mode_output.log /tmp/setup_configuration.json || true
      register: resp
      changed_when: resp.stdout is search('Updating /var/lib/irods/version.json')
      failed_when: resp is failed and resp.stderr is not search ('Post-install test failed')

# XXX - Workaround for https://github.com/irods/irods/issues/8297
    - name: Fix core.re
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |
          if grep --quiet 'tmp-{{ inventory_hostname_short }}' /etc/irods/core.re; then
            sed --in-place \
              's/tmp-{{ inventory_hostname_short }}/{{ irods_cfg_default_resource_name }}/g' \
              /etc/irods/core.re
            echo changed
          fi
      register: resp
      changed_when: resp.stdout == 'changed'

    - name: Delete newly create stub resource
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |
          set -o errexit
          export IRODS_HOST='{{ irods_cfg_catalog_provider_hosts[0] }}'
          if ilsresc 'tmp-{{ inventory_hostname_short }}'; then
            iadmin rmresc 'tmp-{{ inventory_hostname_short }}'
            echo changed
          fi
      register: resp
      changed_when: resp.stdout == 'changed'
# XXX - ^^^

  rescue:
    - name: Ensure version is missing on failure
      ansible.builtin.file:
        path: "{{ _root_dir }}/var/lib/irods/version.json"
        state: absent

    - name: Fail
      ansible.builtin.fail:

- name: Setup iRODS | configure server
  ansible.builtin.import_tasks: server.yml
