---
- name: Base | prepare
  ansible.builtin.import_playbook: ../_shared/prepare.yml


- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Create irods user
      ansible.builtin.user:
        name: irods
        home: /var/lib/irods

    - name: Create config directory
      ansible.builtin.file:
        path: /etc/irods
        state: directory
        owner: irods
        mode: u+rx

    - name: Create file to not receive ownership
      ansible.builtin.file:
        path: /etc/irods/not_owner_test
        mode: u+r
        state: touch

    - name: Create file to receive ownership
      ansible.builtin.file:
        path: /etc/irods/owner_test
        mode: u+r
        state: touch
