---
- name: Ensure exists database {{ postgresql_db_name }}
  community.postgresql.postgresql_db:
    name: "{{ postgresql_db_name }}"
    port: "{{ postgresql_db_dbms_port }}"

- name: Ensure admin user exists for database {{ postgresql_db_name }}
  community.postgresql.postgresql_user:
    name: "{{ postgresql_db_admin_username }}"
    password: "{{ postgresql_db_admin_password }}"
    db: "{{ postgresql_db_name }}"
    priv: all
    port: "{{ postgresql_db_dbms_port }}"
  no_log: true

- name: Allow communication with Postgres DBMS
  community.postgresql.postgresql_pg_hba:
    dest: "{{ postgresql_db_dbms_pg_hba }}"
    contype: host
    databases: "{{ postgresql_db_name }}"
    users: "{{ postgresql_db_admin_username }}"
    source: "{{ item if item | ansible.utils.ipaddr else lookup('dig', item) }}/32"
    method: md5
  notify:
    - Reload
  loop: "{{ postgresql_db_client_hosts }}"
