#!/usr/bin/env bash
#
# Updates a transfer volume (upload or download) for a given user.
#
# Usage:
#  add-transfer USER-ID DIR VOL
#
# Arguments:
#  USER-ID  the DB ID for the user who performed the transfer
#  DIR      the direction of the transfer: 'in' for upload and 'out' for
#           download.
#  VOL      the volume of data transferred in bytes.
#
# © 2025 The Arizona Board of Regents on behalf of The University of Arizona.
# For license information, see https://cyverse.org/license.

set -o errexit -o nounset -o pipefail

export PGHOST="$IRODS_DB_HOST"
export PGPORT="$IRODS_DB_PORT"
export PGUSER="$IRODS_DB_USERNAME"
export PGPASSWORD="$IRODS_DB_PASSWORD"

main() {
	userId="$1"
	dir="$2"
	vol="$3"

	psql ICAT <<EOF
INSERT INTO r_transfer_totals(user_id, action, exbibytes, bytes) VALUES ($userId, '$dir', 0, $vol)
ON CONFLICT (user_id, action) DO UPDATE
	SET
		exbibytes = CASE
				WHEN r_transfer_totals.bytes < (2^60)::BIGINT
				THEN r_transfer_totals.exbibytes + EXCLUDED.exbibytes
				ELSE r_transfer_totals.exbibytes + EXCLUDED.exbibytes
					+ r_transfer_totals.bytes / (2^60)::BIGINT
			END,
		bytes = CASE
				WHEN r_transfer_totals.bytes < (2^60)::BIGINT
				THEN r_transfer_totals.bytes + EXCLUDED.bytes
				ELSE r_transfer_totals.bytes % (2^60)::BIGINT + EXCLUDED.bytes
			END;
EOF
}

main "$@"
