#!/usr/bin/env bash
#
# Calls irepl with the given parameters
#
# Usage:
#  irepl-exec ARGS...
#
# Arguments:
#  ARGS  a list of arguments to pass directly to irepl in the format received
#
# Returns:
#  It writes any error message received from irepl to stderr. All other output
#  is written directly to stdout in the format received.
#
# © 2026 The Arizona Board of Regents on behalf of The University of Arizona.
# For license information, see https://cyverse.org/license.

irepl "$@"