---
- name: Verify
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Verify | cyverse.conf default expansion
      ansible.builtin.debug:
        msg: "TODO: implement"

    - name: Verify | .pgpass default expansion
      ansible.builtin.debug:
        msg: "TODO: implement"

    - name: Verify | template custom values
      ansible.builtin.debug:
        msg: "TODO: implement"

    - name: Verify | tasks
      ansible.builtin.debug:
        msg: "TODO: implement"

    - name: Verify | handlers
      ansible.builtin.debug:
        msg: "TODO: implement"