FROM test-env-base:alma9

ARG DBMS_HOST=dbms_configured
ARG DBMS_PORT=5432
ARG IRODS_SYSTEM_GROUP=irods
ARG IRODS_SYSTEM_USER=irods
ARG IRODS_ZONE_PASSWORD=rods

### Create service script
RUN \
	--mount=target=/tmp/service.sh.template,source=irods-consumer/scripts/service.sh.template \
	--mount=target=/tmp/prep-svc-script,source=irods-consumer/scripts/prep-svc-script.sh \
	/tmp/prep-svc-script

# The service script tracks iRODS with a lock file, and EL9 lacks this directory.
RUN mkdir --parents /var/lock/subsys

COPY irods-provider/config/profile-irods.sh /etc/profile.d/irods.sh

CMD [ "/service.sh" ]
