---
- name: Ensure ansible required packages installed
  ansible.builtin.package:
    name:
      - iproute2
      - python3-firewall
    state: present

- name: Retrieve host info
  ansible.builtin.setup:
    gather_subset:
      - default_ipv4

- name: Ensure ufw is not installed
  ansible.builtin.package:
    name: ufw
    state: absent

- name: Ensure firewalld is installed
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Ensure firewalld is running
  ansible.builtin.service:
    name: firewalld
    enabled: true
    state: started
  tags: molecule-idempotence-notest

- name: Install service description
  ansible.builtin.template:
    src: templates/service.xml.j2
    dest: /etc/firewalld/services/{{ firewalld_service_name }}.xml
    owner: root
    group: root
    mode: u+r
  notify: Reload firewalld

- name: Install ipsets
  ansible.builtin.template:
    src: templates/ipset_{{ item }}.xml.j2
    dest: /etc/firewalld/ipsets/{{ firewalld_service_name }}_{{ item }}.xml
    owner: root
    group: root
    mode: u+r
  notify: Reload firewalld
  loop:
    - admin
    - system
    - external

- name: Install maintenance zone
  ansible.builtin.template:
    src: templates/zone_maintenance.xml.j2
    dest: /etc/firewalld/zones/{{ firewalld_service_name }}_maintenance.xml
    owner: root
    group: root
    mode: u+r
  notify: Reload firewalld

- name: Install block zone
  ansible.builtin.template:
    src: templates/zone_block.xml.j2
    dest: /etc/firewalld/zones/block.xml
    owner: root
    group: root
    mode: u+r
  notify: Reload firewalld

- name: Install operation zone
  ansible.builtin.template:
    src: templates/zone_operation.xml.j2
    dest: /etc/firewalld/zones/{{ firewalld_service_name }}_operation.xml
    owner: root
    group: root
    mode: u+r
    force: false
  notify: Reload firewalld
