#!/usr/bin/env bash
#
# This script builds the ansible-tester image.
#
# © 2025 The Arizona Board of Regents on behalf of The University of Arizona.
# For license information, see https://cyverse.org/license.

set -o errexit -o nounset -o pipefail

#shellcheck source=testing/portability.inc
. "$(cd -- "$(dirname -- "$0")" && pwd -P)"/../portability.inc

EXEC_NAME="$(ds_canonicalize "$0")"
readonly EXEC_NAME

declare BaseDir

main()
{
  BaseDir="$(dirname "$EXEC_NAME")"

  local cfg="$1"

  if [[ -z "$cfg" ]]; then
    printf 'An environment variable include file is needed.\n' >&2
    return 1
  fi

  if ! [[ "$cfg" =~ ^/ ]]; then
    cfg="$(pwd)"/"$cfg"
  fi

  # shellcheck disable=SC1090
  . "$cfg"

  trap 'rm -f "$BaseDir"/requirements.txt "$BaseDir"/requirements.yml' EXIT
  cp -n "$BaseDir"/../../requirements.txt "$BaseDir"/../../requirements.yml "$BaseDir"/

  local buildArgs=(
#    --no-cache
    --build-arg=IRODS_CLERVER_PASSWORD="$IRODS_CLERVER_PASSWORD"
    --platform=linux/amd64
    --tag=ansible-tester )

  docker buildx build "${buildArgs[@]}" "$BaseDir"
}

main "$@"
