#!/usr/bin/env bash
#
# Usage:
#  run INSPECT PRETTY VERBOSE INVENTORY COLLECTION SETUP
#
# Parameters:
#  COLLECTION  the absolute path to the collection whose playbook is being
#              tested
#  INSPECT     if this is set to any value, a shell will be opened that allows
#              access to the volumes in the env containers.
#  INVENTORY   the inventory to test against
#  PLAYBOOK    (OPTIONAL) the name of the playbook being tested.
#  PRETTY      if this is set to any value, more info is dumped and newlines in
#              output are expanded.
#  SETUP       a comma-separated list of playbooks to be run, in order, prior to
#              the playbook under test PLAYBOOK
#  VERBOSE     if this is set to any value, ansible will generate verbose output
#
# Environment Variables:
#  DBMS_HOST                 The hostname of the PostgreSQL server to connect to
#  ENV_NAME                  The docker environment to join
#  IRODS_PROVIDER_CONF_HOST  The host name of the iRODS catalog service provider
#                            to connect to
#  IRODS_ZONE_NAME           The name of the iRODS zone inside the testing
#                            environment
#
# © 2025 The Arizona Board of Regents on behalf of The University of Arizona.
# For license information, see https://cyverse.org/license.

set -o errexit -o nounset -o pipefail

main() {
	local inspect="$1"
	local pretty="$2"
	local verbose="$3"
	local inventory="$4"
	local collection="$5"
	local setup="$6"

	local playbook
	if (( $# >= 7 )); then
		playbook="$7"
	fi

	collection="$(realpath "$collection")"

	docker run --interactive --rm --tty \
		--env IRODS_HOST="$IRODS_PROVIDER_CONF_HOST" \
		--env IRODS_ZONE_NAME="$IRODS_ZONE_NAME" \
		--env PGHOST="$DBMS_HOST" \
		--network "$DOMAIN" \
		--volume "$collection":/root/.ansible/collections/ansible_collections/cyverse/ds:ro \
		--volume "$collection"/playbooks:/playbooks-under-test:ro \
		ansible-tester "$inspect" "$pretty" "$verbose" "$inventory" "$setup" "$playbook"
}

main "$@"
