---
name: cyverse

services:
  irods-rs:
    image: irods-rs
    env_file: .env
    build:
      context: build
      dockerfile: Dockerfile
      args:
        IRODS_HOST_UID: ${IRODS_HOST_UID}
        IRODS_SERVER_PORT_RANGE_START: ${IRODS_SERVER_PORT_RANGE_START}
        IRODS_SERVER_PORT_RANGE_END: ${IRODS_SERVER_PORT_RANGE_END}
        IRODS_VAULT_PATH: ${IRODS_VAULT_PATH}
        IRODS_ZONE_PORT: ${IRODS_ZONE_PORT}
    network_mode: host
    restart: on-failure
    shm_size: 500mb
    volumes:
      - type: bind
        source: /usr/share/zoneinfo/America/Phoenix
        target: /etc/localtime
        read_only: true
      - type: bind
        source: ${IRODS_VAULT_PATH}
        target: ${IRODS_VAULT_PATH}
      - type: bind
        source: /etc/irods
        target: /etc/irods
      - type: bind
        source: /var/lib/irods/.irods
        target: /var/lib/irods/.irods
      - type: bind
        source: /var/lib/irods/msiExecCmd_bin
        target: /var/lib/irods/msiExecCmd_bin
        read_only: true