---
name: cyverse

services:
  irods-rs:
    image: irods-rs
    env_file: .env
    build:
      context: src
      dockerfile: Dockerfile
      args:
        IRODS_HOST_UID: ${IRODS_HOST_UID}
    network_mode: host
    restart: on-failure
    shm_size: 500mb
    volumes:
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
      - type: bind
        source: vault
        target: /irods_vault
      - type: bind
        source: config/etc
        target: /etc/irods
      - type: bind
        source: config/var/irods_environment.json
        target: /var/lib/irods/.irods/irods_environment.json
        read_only: true
