---
platforms:
  - name: provider-cfg
    image: provider
    dockerfile: provider/Dockerfile
    pre_build_image: false
    command: /lib/systemd/systemd
    hostname: provider.molecule
    privileged: true
    tty: true
    shm_size: 256m
    docker_networks:
      - name: molecule
    networks:
      - name: molecule
    network_mode: molecule
    purge_network: true
  - name: consumer
    image: ubuntu:bionic
    hostname: consumer.molecule
    docker_networks:
      - name: molecule
    networks:
      - name: molecule
    network_mode: molecule
    purge_network: true
  - name: provider-uncfg
    image: ubuntu:bionic
    hostname: provider-uncfg
provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        vars:
          irods_cfg_validate: true
      irods_resource:
        vars:
          irods_cfg_catalog_provider_hosts:
            - provider.molecule
          irods_cfg_catalog_service_role: consumer
        hosts:
          consumer:
            irods_cfg_host: localhost
      irods_catalog:
        vars:
          irods_cfg_catalog_service_role: provider
        hosts:
          provider-uncfg:
            irods_cfg_database:
              db_odbc_driver: PostgreSQL Unicode
              db_password: testpassword
              db_username: irods
            irods_cfg_host: localhost
            pg_hba_path: /etc/postgresql/10/main/pg_hba.conf
