---
- name: Create ICAT DB
  hosts: dbms_primary
  run_once: true
  become: true
  become_user: postgres
  gather_facts: false
  tasks:
    - name: Create DB on primary DBMS
      ansible.builtin.import_role:
        name: cyverse.ds.postgresql_db
      vars:
        postgresql_db_dbms_pg_hba: "{{ _dbms_pg_hba }}"
        postgresql_db_dbms_port: "{{ _dbms_port }}"
        postgresql_db_name: ICAT
        postgresql_db_admin_username: "{{ _dbms_irods_username }}"
        postgresql_db_admin_password: "{{ _dbms_irods_password }}"
        postgresql_db_client_hosts: "{{ groups['irods_catalog'] }}"
