---
- name: Create ICAT DB
  hosts: dbms_primary
  run_once: true
  become: true
  become_user: postgres
  tasks:
    - name: Create DB on primary DBMS
      ansible.builtin.import_role:
        name: cyverse.ds.postgresql_db
      vars:
        postgresql_db_dbms_port: "{{ _dbms_port }}"
        postgresql_db_name: ICAT
        postgresql_db_admin_user: "{{ _dbms_irods_username }}"
        postgresql_db_admin_password: "{{ _dbms_irods_password }}"
