---
- name: Provision
  ansible.builtin.import_playbook: irods_provision.yml


- name: Ensure catalog service providers are started
  hosts: irods_catalog
  become: "{{ _irods_become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  tasks:
    - name: Start iRODS
      cyverse.ds.irods_ctl:


- name: Create clerver user
  hosts: irods_resource:!irods_catalog
  become: "{{ _irods_become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  vars:
    admin_user: "{{ hostvars[groups['irods_catalog'][0]]['_irods_clerver_user'] }}"
    admin_password: "{{ hostvars[groups['irods_catalog'][0]]['_irods_clerver_password'] }}"
  tasks:
    - name: Create clerver user
      delegate_to: localhost
      become: false
      cyverse.ds.irods_user:
        name: "{{ _irods_clerver_user }}"
        type: rodsadmin
        state: present
        password: "{{ _irods_clerver_password }}"
        host: "{{ groups['irods_catalog'][0] }}"
        port: "{{ _irods_zone_port }}"
        admin_user: "{{ admin_user }}"
        admin_password: "{{ admin_password }}"
        zone: "{{ _irods_zone_name }}"

    - name: Ensure clerver user is in group rodsadmin
      delegate_to: localhost
      become: false
      cyverse.ds.irods_group_member:
        group: rodsadmin
        users:
          - "{{ _irods_clerver_user }}"
        state: present
        host: "{{ groups['irods_catalog'][0] }}"
        port: "{{ _irods_zone_port }}"
        admin_user: "{{ admin_user }}"
        admin_password: "{{ admin_password }}"
        zone: "{{ _irods_zone_name }}"

    - name: Set up iRODS
      ansible.builtin.include_role:
        name: cyverse.ds.irods_cfg
        tasks_from: setup_irods.yml
      vars:
        irods_cfg_catalog_provider_hosts: "{{ groups['irods_catalog'] }}"
        irods_cfg_catalog_service_role: consumer
        irods_cfg_client_server_policy: "{{ _irods_client_server_policy }}"
        irods_cfg_cmd_scripts:
          - files/irods/var/lib/irods/msiExecCmd_bin/*
        irods_cfg_database: null
        irods_cfg_default_dir_mode: "{{ _irods_default_dir_mode }}"
        irods_cfg_default_file_mode: "{{ _irods_default_file_mode }}"
        irods_cfg_default_hash_scheme: "{{ _irods_default_hash_scheme }}"
        irods_cfg_default_number_of_transfer_threads: >-
          {{ _irods_default_number_of_transfer_threads }}
        irods_cfg_default_resource_directory: "{{ _irods_default_vault }}"
        irods_cfg_default_resource_name: "{{ _irods_default_resource }}"
        irods_cfg_federation: "{{ _irods_federation }}"
        irods_cfg_host_entries: >-
          {{ [] if _irods_host_aliases | count == 0 else
            [
              {
                'address_type': 'local',
                'addresses': [inventory_hostname] + _irods_host_aliases
              }
            ] }}
        irods_cfg_negotiation_key: "{{ _irods_negotiation_key }}"
        irods_cfg_re:
          additional_rulebases:
            - cve
            - cyverse_core
            - cyverse_housekeeping
        irods_cfg_restart_allowed: "{{ _irods_restart_allowed }}"
        irods_cfg_rulebases_static:
          - files/irods/etc/irods/*.re
        irods_cfg_rulebases_templated:
          - templates/irods/etc/irods/*.re.j2
        irods_cfg_server_control_plane_key: "{{ _irods_server_control_plane_key }}"
        irods_cfg_server_control_plane_port: "{{ _irods_server_control_plane_port }}"
        irods_cfg_server_port_range_end: "{{ _irods_server_port_range_end }}"
        irods_cfg_server_port_range_start: "{{ _irods_server_port_range_start }}"
        irods_cfg_system_account_name: "{{ _irods_service_account_name }}"
        irods_cfg_system_group_name: "{{ _irods_service_group_name }}"
        irods_cfg_transfer_buffer_size_for_parallel_transfer: >-
          {{ _irods_parallel_transfer_buffer_size }}
        irods_cfg_zone_key: "{{ _irods_zone_key }}"
        irods_cfg_zone_name: "{{ _irods_zone_name }}"
        irods_cfg_zone_password: "{{ _irods_clerver_password }}"
        irods_cfg_zone_port: "{{ _irods_zone_port }}"
        irods_cfg_zone_user: "{{ _irods_clerver_user }}"

    - name: Start iRODS
      cyverse.ds.irods_ctl:


- name: Create storage resources
  ansible.builtin.import_playbook: irods_storage_resources.yml
