---
- name: Create vaults
  hosts: irods_resource:!unmanaged_systems
  become: true
  tasks:
    - name: Create vault directory
      ansible.builtin.file:
        path: "{{ item.vault }}"
        follow: true
        owner: "{{ _irods_service_account_name }}"
        group: "{{ _irods_service_group_name }}"
        mode: 'u=rwx'
        state: directory
      with_items: "{{ _irods_storage_resources }}"

- name: Create storage resources
  hosts: irods_resource
  tasks:
    - name: Define storage resource
      delegate_to: localhost
      cyverse.ds.irods_unixfilesystem_resource:
        name: "{{ item.name }}"
        host: "{{ inventory_hostname }}"
        vault: "{{ item.vault }}"
        context: "{{ item.context }}"
        status: up
        zone: "{{ _irods_zone_name }}"
        username: "{{ _irods_clerver_user }}"
        password: "{{ _irods_clerver_password }}"
      with_items: "{{ _irods_storage_resources }}"

- name: Initialize free space
  ansible.builtin.import_playbook: irods_free_space.yml
