---
- name: Restart iRODS service
  hosts: irods
  become: "{{ _irods_become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  tasks:
    - name: Restart
      ansible.builtin.include_tasks: tasks/irods/restart.yml
      vars:
        restart_op: always
  tags:
    - non_idempotent
