---
- name: Install and configure rsyslog for iRODS
  hosts: irods
  become: true
  tasks:
    - name: Enable notifications
      ansible.builtin.set_fact:
        _enable_notifications: true
      tags:
        - no_testing

    - name: Ensure Ubuntu package repo is update to date
      when: ansible_distribution == 'Ubuntu'
      ansible.builtin.apt:
        update_cache: true
      tags:
        - non_idempotent

    - name: Install rsyslog
      ansible.builtin.package:
        name: rsyslog
        state: present

    - name: Configure for iRODS
      ansible.builtin.copy:
        dest: /etc/rsyslog.d/00-irods.conf
        content: |
          $FileCreateMode 0644
          $DirCreateMode 0755
          $Umask 0000
          $template irods_format,"%msg%\n"
          :programname,startswith,"irodsServer" /var/log/irods/irods.log;irods_format
          & stop
          :programname,startswith,"irodsDelayServer" /var/log/irods/irods.log;irods_format
          & stop
          :programname,startswith,"irodsAgent" /var/log/irods/irods.log;irods_format
          & stop
        mode: u+r
      notify: Reload rsyslog

    - name: Configure log rotations for iRODS
      ansible.builtin.template:
        src: irods/etc/logrotate.d/irods.j2
        dest: /etc/logrotate.d/irods
        mode: u+r

  handlers:
    - name: Reload rsyslog
      when: _enable_notifications | d(false)
      ansible.builtin.service:
        name: rsyslog
        state: reloaded