---
- name: Remove MD Repo rule logic
  hosts: irods
  become: "{{ _irods_become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  pre_tasks:
    - name: Remove mdrepo rule bases
      ansible.builtin.file:
        path: /etc/irods/{{ item }}
        state: absent
      notify: Reload rules
      loop:
        - mdrepo.re
        - mdrepo-env.re

  post_tasks:
    - name: Remove md-repo-touch-obj
      ansible.builtin.file:
        path: /var/lib/irods/msiExecCmd_bin/md-repo-touch-obj
        state: absent

  handlers:
    - name: Reload rules
      ansible.builtin.file:
        path: /etc/irods/core.re
        state: touch
        mode: u+r


- name: Configure for MD Repo CLI
  hosts: irods_catalog
  become: "{{ _irods_become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  run_once: true
  gather_facts: false
  tasks:
    - name: Create MD Repo CLI account
      when: _mdrepo_cli_account | length > 0
      delegate_to: localhost
      become: false
      cyverse.ds.irods_user:
        name: "{{ _mdrepo_cli_account }}"
        info: MD Repo command line interface
        password: ''
        state: present
        host: "{{ groups['irods_catalog'][0] }}"
        port: "{{ _irods_zone_port }}"
        admin_user: "{{ _irods_clerver_user }}"
        admin_password: "{{ _irods_clerver_password }}"
        zone: "{{ _irods_zone_name }}"
