---
- name: Start the SFTP services
  hosts: sftp
  become: true
  tags:
    - no_testing
  tasks:
    - name: Start sftpgo
      ansible.builtin.service:
        name: sftpgo
        state: started
        enabled: true
