---
- name: Reboot
  when:
    - _notifications_enabled | d(false)
    - >-
      postgresql_restart_allowed is cyverse.ds.warn_if_false(
        inventory_hostname + ' skipped, REBOOT REQUIRED FOR SETTINGS TO TAKE')
  ansible.builtin.reboot:

- name: Reload postgres
  ansible.builtin.service:
    name: postgresql
    state: reloaded

- name: Restart postgres
  when: >-
    postgresql_restart_allowed is cyverse.ds.warn_if_false(
      inventory_hostname + ' skipped, POSTGRESQL RESTART REQUIRED FOR SETTINGS TO TAKE')
  ansible.builtin.service:
    name: postgresql
    state: restarted
