---
webdav_amqp_host: "{{ groups['amqp'][0] }}"

webdav_cache_dir: /cache_vol
webdav_cache_size: 500
webdav_cache_max_file_size: 10

webdav_irods_username: rods
webdav_irods_password: password

webdav_restart_allowed: true

webdav_tls_chain: "{{ tls_root_cert }}"
webdav_tls_chain_file: /etc/httpd/testing.crt
webdav_tls_cert: "{{ tls_cert_default }}"
webdav_tls_cert_file: /tmp/cert/testing.crt
webdav_tls_key: "{{ tls_key_default }}"
webdav_tls_key_file: /tmp/key/testing.key
