---
- name: Converge | Stop iRODS
  hosts: all
  gather_facts: false
  become: true
  become_user: irods
  tasks:
    - name: Stop iRODS
      ansible.builtin.command: /var/lib/irods/irodsctl stop
      register: resp
      changed_when: false
      failed_when: false


- name: Converge | update version lock
  hosts: all
  gather_facts: false
  tasks:
    - name: Remove 4.3.1 version lock
      ansible.builtin.command:  # noqa: command-instead-of-module
        cmd: >-
          yum versionlock delete
            irods-database-plugin-postgres-4.3.1
            irods-icommands-4.3.1
            irods-runtime-4.3.1
            irods-server-4.3.1
      register: resp
      changed_when: resp.stdout is regex('Deleting versionlock')

    - name: Add 4.3.5 version lock
      community.general.yum_versionlock:
        name:
          - irods-database-plugin-postgres-4.3.5
          - irods-icommands-4.3.5
          - irods-runtime-4.3.5
          - irods-server-4.3.5
        state: present
# XXX - Due to https://github.com/ansible-collections/community.general/issues/4470, this isn't
# idempotent.
      tags: molecule-idempotence-notest
# XXX - ^^^


- name: Converge | upgrade iRODS packages
  hosts: all
  gather_facts: false
  tasks:
    # irods-server doesn't declare irods-icommands, so it's upgraded explicitly.
    - name: Upgrade
      ansible.builtin.dnf:
        name:
          - irods-database-plugin-postgres
          - irods-icommands
          - irods-runtime
          - irods-server
        state: latest  # noqa: package-latest


- name: Converge | upgrade iRODS
  hosts: all
  become: true
  become_user: irods
  gather_facts: false
  tasks:
    - name: Restart iRODS
      ansible.builtin.command: /var/lib/irods/irodsctl start
      changed_when: false

    - name: Ensure configuration is correct
      ansible.builtin.include_role:
        name: cyverse.ds.irods_cfg
        tasks_from: main.yml
