---
- name: Verify
  hosts: all
  tasks:
    - name: Validate deposition of server_config.json
      ansible.builtin.include_tasks: ../_irods_cfg_shared/tasks/validate_deposition.yml
      vars:
        cfg_path: /etc/irods/server_config.json
        schema_path: /var/lib/irods/configuration_schemas/v4/server_config.json

    - name: Verify old config not deposited
      ansible.builtin.stat:
        path: /etc/irods/{{ item }}
      register: response
      failed_when: response.stat.exists
      loop:
        - host_access_control_config.json
        - hosts_config.json

    - name: Validate deposition of irods_environment.json
      ansible.builtin.include_tasks: ../_irods_cfg_shared/tasks/validate_deposition.yml
      vars:
        cfg_path: /var/lib/irods/.irods/irods_environment.json
        schema_path: /var/lib/irods/configuration_schemas/v4/service_account_environment.json

    - name: Check service_account.config deposition
      ansible.builtin.stat:
        path: /etc/irods/service_account.config
      register: response
      failed_when: >-
        not response.stat.exists or
        response.stat.pw_name != 'irods' or
        response.stat.gr_name != 'irods'
