#!/usr/bin/env bash
#
# Usage:
#  clean INC_FILE
#
# PARAMETERS:
#  INC_FILE  The absolute path to a file including the build time environment
#            variables. See README.md for details.
#
# Deletes the four docker images.


main()
{
  local cfg="$1"

  if [ -z "$cfg" ]
  then
    printf 'An environment variable include file is needed.\n' >&2
    return 1
  fi

  if ! [[ "$cfg" =~ ^/ ]]
  then
    cfg="$(pwd)"/"$cfg"
  fi

  #shellcheck disable=1090
  . "$cfg"

  local images
  readarray -t images \
    < <(docker images --format '{{.Repository}}:{{.Tag}}' --filter reference="$ENV_NAME"-*)

  if [[ -n "${images-}" ]]; then
    docker rmi "${images[@]}"
  fi

  local bases
  readarray -t bases < <(docker images --quiet --filter reference=test-env-base)

  if [[ -n "${bases-}" ]]; then
    docker rmi "${bases[@]}"
  fi
}


main "$@"
